.releaserc.json

- `...`
This PR is a:
About this PR:
complexity.
```
```

fix: fix the semantic release workflow

---

poetry.lock
pyproject.toml
src/rago/augmented/base.py
src/rago/augmented/hugging_face.py
src/rago/core.py
src/rago/db/base.py
src/rago/db/faiss.py
src/rago/generation/base.py
src/rago/generation/hugging_face.py
src/rago/generation/llama3.py

- `...`
This PR is a:
About this PR:
complexity.
```
```

feat: Implement type checking with typeguard

---

src/rago/augmented/base.py
src/rago/augmented/hugging_face.py
src/rago/db/base.py
src/rago/db/faiss.py
src/rago/generation/base.py
src/rago/generation/hugging_face.py
src/rago/generation/llama3.py
src/rago/retrieval/base.py

- `...`
This PR is a:
About this PR:
complexity.
```
```

fix: Improve the usage of typeguard

---

src/rago/core.py
src/rago/generation/base.py
src/rago/generation/hugging_face.py
src/rago/generation/llama3.py
src/rago/retrieval/base.py
tests/test_llama3.py

- `...`
This PR is a:
About this PR:
complexity.
```
```

refactor: make Hugging Face and model device selection optional defaulting to CUDA

---

README.md
poetry.lock
pyproject.toml

- `...`
This PR is a:
About this PR:
complexity.
```
```

fix: Fix packaging for gpu and cpu

---

README.md
src/rago/augmented/__init__.py
src/rago/augmented/base.py
src/rago/augmented/experimental/__init__.py
src/rago/augmented/experimental/gemini.py
src/rago/augmented/experimental/openai.py
src/rago/augmented/hugging_face.py
src/rago/core.py
src/rago/db/base.py
src/rago/db/faiss.py
tests/test_gemini.py
tests/test_hugging_face.py
tests/test_llama.py
tests/test_openai.py

This PR aims to:
* Add attribute for storing intermediate results from the pipeline
* rename variable `k` to `top_k`
* move openai and gemini augmented classes to the `experimental` package.

feat: Add attribute for storing intermediate results from the pipeline

---

poetry.lock
pyproject.toml
src/rago/core.py
src/rago/generation/base.py
src/rago/generation/gemini.py
src/rago/generation/hugging_face.py
src/rago/generation/llama.py
src/rago/generation/openai.py
tests/models.py
tests/test_gemini.py
tests/test_openai.py

- `...`
This PR is a:
About this PR:
complexity.
```
```

feat: Add initial support for structured output

---

src/rago/augmented/openai.py
src/rago/augmented/spacy.py
src/rago/retrieval/file.py

- `...`
This PR is a:
About this PR:
complexity.
```
```

fix: Fix caching

---

.gitignore
conda/dev.yaml
src/rago/augmented/base.py
src/rago/generation/base.py
src/rago/retrieval/base.py

- `...`
This PR is a:
About this PR:
complexity.
```
```

fx: Fix undesired weekref `logs` attribute from default value

---

src/rago/generation/base.py
src/rago/generation/openai.py

- `...`
This PR is a:
About this PR:
complexity.
```
```

feat: Add support for extra parameters for RAG generation

---

src/rago/augmented/base.py
src/rago/generation/base.py
tests/test_openai.py

- `...`
This PR is a:
About this PR:
complexity.
```
```

fix: Fix default values

---

poetry.lock
pyproject.toml
src/rago/augmented/base.py
src/rago/augmented/openai.py
src/rago/augmented/spacy.py
src/rago/generation/gemini.py
tests/test_openai.py
tests/test_spacy.py

- `...`
This PR is a:
About this PR:
complexity.
```
```

fix: Fix get_embedding in the augmented classes

---

.github/workflows/docs.yaml
.github/workflows/main.yaml
.github/workflows/release.yaml
conda/ci.yaml
conda/dev.yaml
poetry.lock
pyproject.toml

- `...`
This PR is a:
About this PR:
complexity.
```
```

chore(ci): Create separated conda env file for ci

---

docs/contributing.md

Fix #42 
This PR corrects the typing error in the conda environment creation command in the `contributing` documentation. :)
This PR is a:

docs(contributing): correct the conda `env` command in contributing docs

---

README.md

This PR improves the documentation such that it is more clear for the user to understand how to initialise a Rago object and run it.
This PR is a:

docs(usage) Improve the README for the usage of Rago

---

README.md

Fix #41 
This PR adds OSL's Discord Server's Link to the Index and README.md pages
This PR is a:
```

docs(links): Add OSL's Discord Server Link

---

README.md

PR #47 improves the documentation of llama model usage in Rago but the library import structure was incorrect in that PR. This PR corrects it.

docs(usage): Correct the import structure in usage example

---

.pre-commit-config.yaml
.prettierignore
.prettierrc.yaml
CODE_OF_CONDUCT.md
README.md

- `...`
This PR is a:
About this PR:
complexity.
```
```

docs: Add information about roadmap

---

tests/conftest.py
tests/test_ret_text_splitter.py

This PR is to just make some minor improvements in our project which I came across while looking at the test files 
@xmnlab please review!
This PR is a:

Fix: Typo in Tests files

---

pyproject.toml
scripts/install-dev.sh

- `...`
This PR is a:
About this PR:
complexity.
```
```

fix: packaging and releasing steps
